### ISSUE TITLE
Add camera FOv setting via top/bottom method

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/Gigavision#10]
Let user set the vertical FOV by clicking a button to mark the top and then bottom of the camera FOV then calculate the rest of the parameters from this (as an alternative to the current automatic method)

**Comment by chuong** [comment]
This has been implemented. User will need to select a feature point firstly by Shift + mouse click, then move camera to a new position and select the same feature point by Ctrl + mouse click. The provide displacement of feature point in pixels with respect to the change in pan-tilt position of the camera.
