### ISSUE TITLE
Write settings file to capture folder

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/Gigavision#11]
Program should save a file (format? yml, xml, csv, txt) that at the very least has the number of rows and columns and which camera settings file was used. Might be good to include any other data that might vary between captures.

This will be used for 
(1) Stitcher needs to know how many rows and columns and capture order (i.e. "rows down" or 
"columns, left-> right", etc)
(2) If camera settings change between captures this breaks the entire downstream stitching and playback pipeline and requires creation of a new "cam config" file for the stitcher and playback so we'll want to be able to easily audit when changes have happened (since they should happen as infrequently as possible).

**Comment by chuong** [comment]
Settings are now saved to (image_folder)/_data/PanConfig.yml.
