### ISSUE TITLE
Features needed for remote deployment

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/Gigavision#14]
* __VNC (done)__
  * User can log in from ANU and view desktop
  * Logging out of VNC doesn't end auto capture or GUI running
* __IP of Pi should be fixed at 192.168.1.120 (done)__

* __Auto running of system__
  * On power up, GUI is loaded and pano starts taking images automatically with correct settings and profile
  * System will capture one pano per hour during set hours
  * For "one pano per day" system needs to handle start/stop times correctly:
    * START time should denote time that first pano is taken.
    *  STOP time should deonte time that last pano is taken. 
    * Examples:
       * If START is "12" and STOP is "12" system will take one full pano.* 
       * If START is 12 and STOP is 1pm it will know to take an image at 12 and 1, etc
  * Need option to choose local or remote storage (or both if possible and not too long to implement)
  * Capture location
      * Config file must hold root location for capture and not require user to set this (but provide option for user to change save path with button or field)
      * Capture location must support mapped file paths and mapped file path must be persistent and available for file storage between power cycles.
      * Ideally there would be a local location as a fallover if remote path becomes available
   * File and folder structure
      * Once root file capture is set, panos will capture to the correct TimeStream standard folder following these requirements:
      * GUI must have field to let user set TimeStream Name
      * Folder Path: **rootpath/YYYY/MM/DD/HH/TimeStreamName_YYYY_MM_HH_00/** _(minute value in file name will be set to zero for current implementation until will implement ability to take multiple panos in an hour)_
      * File naming:
        * File will all be in the folder under current hour for each pano
        * File name will be: __TimeStreamName_TimeStamp_####.jpg__ (where #### is fixed-length image number )
        * For example:ARB-HILL-GV~fullres_2015_01_25_10_12_00_00_0002.jpg
* __Handle external power cycling__
  * At end of day, pi prepares for power off
  * External power will turn on at 6:30 AM (first pano at 7AM)
  * External power will be cut at 7:45PM (last pano at 7PM)

* __System must stop capturing if drive space is less than a value set in the GUI__
  * To prevent fatal problems with local file system filling up, the GUI needs to stop capturing if available file space goes below an amount set in the GUI
  * If there are problems querying the remote mapped server for file size we can skip detecting space availability on mapped drives for now (since we aren't currently space limited on them)

**Comment by chuong** [comment]
So far, most of this list has been implemented, except for time stream name.

**Comment by chuong** [comment]
TimeStreamName has now implemented.

**Comment by chuong** [comment]
Resolved previously.
