### ISSUE TITLE
Config page: Need to clarify what "enabled" button turns off

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/Gigavision#2]
If I disable the DSLR, for example, the FTP uploaded boxes stay checked. Does the DSLR and picam ftp happen in separate processes? If turn it off for the DSLR does it stay on for the picam?
I was going to suggest graying out all fields but a user might want to config the camera while it is off so this isn't a good solution

Maybe best to have "disabled" appear in big test somewhere to the right of the FTP details when a camera is disabled?

**Comment by gdunstone** [comment]
this has been done.
