### ISSUE TITLE
GUI software should have config file

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/Gigavision#24]
Changes from previous session should be loaded.
This should probably include:
(1) Current cam and ptz config file (and the settings in the program should be loaded automatically if they are valid)
(2) Save file paths (local and remote)
(3) Any other primary settings not covered by camera/ptz config file that will get auto loaded

**Comment by TimeScience** [comment]
Warn user on software close if unsaved changes have been made

**Comment by chuong** [comment]
Resolve with @a1368b3, @6bcab9d and @87b5ae7
