### ISSUE TITLE
Loop feature doesn't work - HIGH PRIORITY

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/Gigavision#29]
System doesn't currently do timelapse because the "loop" feature doesn't work. it only takes one picture when the system boots and then stops. I'd like to start shooting real timelapse gigapans asap but we can't without it looping.
thanks

**Comment by chuong** [comment]
This is strange. I will try to come this late afternoon.

**Comment by chuong** [comment]
This has been resolved.
