### ISSUE TITLE
FTP issues

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/Gigavision#3]
We should map out how FTP works for both cameras and make sure it is as efficient as possible.

For example when the camera upload has failed for some reason as it did last night, there is a backlog of images that get uploaded. but the upload of archived images seems to take precedence over upload of the the current cameraip.html file and the current webcam image. This should be switched so that webcam image and IP are always uploaded and the syncing of archives happens as more of a background process.

**Comment by gdunstone** [comment]
This was fixed ages ago.
