### ISSUE TITLE
System still not capturing reliably

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/Gigavision#30]
worked sporadically through noon on the 19th but not since then. haven't restarted so it _shouldn't_ be a drive mapping issue (but who knows). isn't saving to local storage either.

**Comment by chuong** [comment]
Hi Tim,
I will try to have a look at this today if I have time. I will be away
whole next week.
Chuong

**Comment by gdunstone** [comment]
system is capturing reliably now
