### ISSUE TITLE
GV images MUST upload in folder by hour

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/Gigavision#35]
Sync can't just dump all GV images into one folder. All images for each panorama must be inside a parent named down to the hour and preserving (semi) standard timestream naming and folder formatting. 
Example for hilltop camera:
_NationalArboretum\shared\phenocams\gigavision\ARB-GV-HILL-1\2015\2015_12\2015_12_07\2015_12_07_10\ _all images go in here_

**Comment by gdunstone** [comment]
this is fixed in latest version.
also is duplicate.,
