### ISSUE TITLE
Add folder for each gigapan

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/Gigavision#37]
We really need captured images to go into their own folder for each gigapan. folders should be named in standard TS format down to the hour. I know this isn't the paradigm for the eyepicam but it is a mess to have 180 jpg images from each capture with nor organization. didn't you have a setting on the picam to capture onto the pi in timestream format anyway? can you implement that so they go in folders at least?

**Comment by gdunstone** [comment]
this is fixed in the latest version.
