### ISSUE TITLE
URGENT - Verify folder naming is correct and data is not being overwritten and is being captured correctly

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/Gigavision#49]
the 5pm files today were saved to the folder 2017_03_24_06
that should be for 6am. this is bad. if data gets written to the wrong folder it is very bad because it means the camera is essentially broken. - please fix ASAP (before noon tomorrow so we can get a good pano by noon)

thanks

**Comment by gdunstone** [comment]
This was actually a timzone bug.
