### ISSUE TITLE
File management

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/Gigavision#5]
We should discuss how to best handle the storage and sync of locally cached files.
I'd think the options should be:
- delete on sync if file present - pi checks server and deletes any local file that is already there
- Delete on sync - each file is locally deleted as soon as it is successfully uploaded (different from previous because if we have a different process on the remote server that is moving files as they are uploaded, the pi won't be able to check which files are on the server to compare what is there with the local set)
- Cache local and never delete - Files are never deleted from the picam
  *\* Would also be nice to have some space reporting (could be a button the user clicks to load the details if this slows things down too much) - should list: \* number of local files; \* how much space there is *estimate of number of captures remaining (count) \* Estimate of captures remaining - time (count of images / frame rate), but formatted nicely (i.e. days, hours minutes left before it is full)
- Cache local, no upload - files are stored on pi but not uploaded (but this shouldn't disable upload for the webcam image)
- Delete all local images button
  *\* (Even better would be an additional option to "delete all files older than..." for space management

**Comment by TimeScience** [comment]
Gareth this never got assigned to you and was under the wrong repo. not sure how much is still relevant.

**Comment by gdunstone** [comment]
Umm. You just need to input bogus login credentials for 3 and 4.
And 1,2,5 happen automatically.
5: Why wouldn't you just delete them when you copy them off the pi if they are stored locally?
I could add a button which gives you the folder full of images as a big local network download.
Ill look at putting the buttons in for file management. 
Can we have these issues on spc-eyepi rather than gigavision?

**Comment by gdunstone** [comment]
This was implemented ages ago. Closing.
